controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    follow_joint_trajectory:
      type: follow_joint_trajectory/FollowJointTrajectory

joint_trajectory_controller:
  ros__parameters:
    joints:
      - ard_motorA
      - ard_motorB
      - ard_motorC
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 20.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false

follow_joint_trajectory:
  ros__parameters:
    default: true
    joints:
      - ard_motorA
      - ard_motorB
      - ard_motorC
